Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [34]:
import numpy as np

In [35]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
a=[1,2,3,4,5]
print("one dimensional NumPy array ",np.array(a))
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
b=[[1,2,3],[4,5,6],[7,8,9]]
print("two dimensional NumPy Array ",np.array((b)))
print("shape of the 2D array is ",np.array((b)).shape)

one dimensional NumPy array  [1 2 3 4 5]
two dimensional NumPy Array  [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of the 2D array is  (3, 3)


In [36]:
# Write a NumPy function to create an array with random values of shape [3,4]
rand=np.random.rand(3,4)
print(rand)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
zeros=np.zeros((3,4))
print(zeros)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
ones=np.ones((3,4))
print(ones)

[[0.77580844 0.64123649 0.90515004 0.64439551]
 [0.7550101  0.57552625 0.12591115 0.63407281]
 [0.17386121 0.75378568 0.8534802  0.84400339]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
array=np.arange(0,10,2)
print(array)

[0 2 4 6 8]


### Basic array operations
- algebraic operations
- logical operations

In [38]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [39]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [40]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(np.sum(a,axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1
print(np.sum(a,axis=1))

[ 6 17 14]
[10 13 14]


In [41]:
# Write a NumPy function to reverse the array 'a'
print(a[::-1,::-1])
# Write a NumPy function to reverse the array 'a' along axis=0
print(a[::-1,:])
# Write a NumPy function to reverse the array 'a' along axis=1
print(a[:,::-1])

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [42]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [43]:
# Write a NumPy function to sort the array 'a'
print(np.sort(a,axis=None))
# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a,axis=0))
# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a,axis=1))
# Write a NumPy function to sort the array 'a' in descending order along axis=0
print(-np.sort(-a,axis=0))

[-4  1  1  3  5  6  8  8  9]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [44]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a,axis=0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a,axis=0))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 1]
 [2 0 2]
 [1 2 0]]


In [45]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b),axis=None))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b),axis=0))
# Note: You can do the same function using stacking, discover and try that :)
print(np.vstack((a,b)))

[-4  6  8  9  3  1  1  8  5 11 16 18 90 37 81 61 48 75]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [46]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [47]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [48]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(a.reshape(1,9))

[[4 6 8 9 3 1 1 8 5]]


In [49]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
print(a[np.newaxis,:])
print(np.expand_dims(a,axis=0))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [50]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [51]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print(a[0])  #indexing by a integer
print(a[1,2]) #indexing by a tuple
print(a[0:2,1:3]) # got a range of subarrays of row 0-1 and colums 1-2

[4 6 0]
1
[[6 0]
 [3 1]]


In [52]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [53]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [54]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
copy=a.copy()
print(copy+1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [55]:
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

import ssl
from urllib.request import urlopen

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
context = ssl._create_unverified_context()
data = urlopen(url, context=context)
iris_2d = np.genfromtxt(data, delimiter=',', dtype = 'float', usecols=(0,1,2,3), encoding='utf-8')

#### Basic Data Analysis

In [58]:
import pandas as pd
# Write a Pandas function to drop rows that contain a missing value.
a=pd.DataFrame(iris_2d)
b=a.dropna()

In [60]:
# Write a Pandas function to find the correlation between the first two columns.
print("Correlation",a[0].corr(a[1]))

Correlation -0.10936924995064935


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean=a[2].mean()
median=a[2].mean()
std=a[2].std()

In [62]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
a['Volume']=(np.pi*a[2]*(a[0]**2))/3
print(a)

       0    1    2    3      Volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [63]:
x = np.arange(4, dtype=np.int64)
ones=np.ones(x.shape)
print(ones)

[1. 1. 1. 1.]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [66]:
x=np.arange(1,10)
array=np.split(x,[4,6])
print(array)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [67]:
x=np.random.randint(0,10,size=(2,5))
max=np.max(x,axis=1)
min=np.min(x,axis=1)
maxind=np.argmax(x,axis=1)
minind=np.argmax(x,axis=1)
print(x)
print("maximum value", max ,"minimum value" , min)
print("maximum index" , maxind , "minimum index" , minind)



[[4 9 4 9 2]
 [3 2 3 2 2]]
maximum value [9 3] minimum value [2 2]
maximum index [1 0] minimum index [1 0]


### Pandas

Run the following load command and solve the following questions

In [68]:
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

import ssl
import pandas as pd
from urllib.request import urlopen
from io import StringIO

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
context = ssl._create_unverified_context()
data = urlopen(url, context=context)
text = data.read().decode('utf-8')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris_df = pd.read_csv(StringIO(text),header=None,names=names)

Q4 Write a Pandas function to find the count of unique species.

In [71]:
print("Unique species count:", iris_df['species'].nunique())


Unique species count: 3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [75]:
bins=[-np.inf,3,5,np.inf]
labels=["small","medium","large"]
iris_df['petal_length_bin']=pd.cut(iris_df['petallength'],bins=bins,labels=labels,right=False)
print(iris_df[['petallength','petal_length_bin']].head())

   petallength petal_length_bin
0          1.4            small
1          1.4            small
2          1.3            small
3          1.5            small
4          1.4            small


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [76]:
print("Most frequent petal lenght:",iris_df['petallength'].mode()[0])

Most frequent petal lenght: 1.5
